



--Query the sum of the populations for all Japanese cities in CITY. The COUNTRYCODE for Japan is JPN.

BEGIN TRANSACTION
CREATE TABLE City(
	ID INT,
	NAME VARCHAR(17),
	COUNTRYCODE VARCHAR(3),
	DISTRICT VARCHAR(20),
	POPULATION INT 
)

SELECT SUM(POPULATION) FROM CITY WHERE COUNTRYCODE = 'JPN'


ROLLBACK TRANSACTION

